---
Name: workflow_actions_styles
---
# admin files
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'symbiote-library/silverstripe-workflow-actions:client/styles/admin.css'

---
Name: workflow_actions_extensions
---
Page:
  extensions:
    - Symbiote\AdvancedWorkflow\Extension\WorkflowFieldCapture
    - Symbiote\AdvancedWorkflow\Extension\ContentApproversExtension
Symbiote\AdvancedWorkflow\DataObjects\WorkflowActionInstance:
  extensions:
    - Symbiote\AdvancedWorkflow\Extension\WorkflowActionInstanceExtension
SilverStripe\CMS\Controllers\CMSPageEditController:
  extensions:
    - Symbiote\AdvancedWorkflow\Extension\RightsideWorkflow
SilverStripe\Forms\GridField\GridFieldDetailForm_ItemRequest:
  extensions:
    - Symbiote\AdvancedWorkflow\Extension\RightsideWorkflow

---
Name: workflow_actions_jobs
Only:
  moduleexists: symbiote/silverstripe-queuedjobs
---
SilverStripe\Core\Injector\Injector:
  Symbiote\QueuedJobs\Services\QueuedJobService:
    properties:
      defaultJobs:
        WorkflowTimeoutJob:
          type: 'Symbiote\AdvancedWorkflow\Jobs\WorkflowTimeoutJob'
          filter:
            JobTitle: 'Workflow Timeout Job'
          construct:
            -
          startDateFormat: 'Y-m-d H:i:s'
          # FREQUENCY OF TIMEOUT CHECKS
          startTimeString: 'now + 1 hour'
          recreate: 1
          # ADMIN EMAIL HERE
          email: 'admin@example.com'